### ISSUE TITLE
Add i18n feature

### ISSUE THREAD

**Issue by vinzv** [BunsenLabs/website#5]
If the website had an i18n feature I'd volunteer on translating it (at least to German).

**Comment by 2ion** [comment]
> If the website had an i18n feature I'd volunteer on translating it (at
> least to German).
Thank you very much for the offer. However, I prefer keeping the page in
one language for now. The main reason is that the maintenance overhead
would increase as translations need to be kept current. While as a
native speaker of German that wouldn't be a problem, I'd like to save
the effort for other things that need doing. Since most German users
should be fairly proficient in the English language anyway, I also do
not see an immediate need.
Closes #5.
